# Generated by Django 4.2.3 on 2023-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Enseignant', 'Enseignant'), ('Autorite UL', 'Autorité UL')], default='Etudiant', max_length=111),
        ),
    ]
