# Generated by Django 4.2 on 2024-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_profile_type_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_profile',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Enseignant', 'Enseignant'), ('Autorite UL', 'Autorité UL')], default='Etudiant', max_length=66),
        ),
    ]
