# Generated by Django 4.2 on 2024-01-07 21:57

import UL.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_profile_type_profile'),
        ('UL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertepointeau',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertebatiment',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertegenerale',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertejardin',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertelampadaire',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertepoubellefosse',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertereposoir',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertewifi',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='arbreisole',
            name='annee_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assainissement',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32631),
        ),
        migrations.AlterField(
            model_name='camera',
            name='date_instal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='espacevert',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiosque',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lampadaire',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loisir',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paneau',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planeau',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointeau',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reposoir',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telecomminication',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voirie',
            name='date_construc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone_ul',
            name='aire',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='zone_ul',
            name='limite',
            field=models.ForeignKey(default=UL.models.Limite, null=True, on_delete=django.db.models.deletion.PROTECT, to='UL.limite'),
        ),
        migrations.DeleteModel(
            name='ArbreReboise',
        ),
    ]
