# Generated by Django 4.2 on 2024-02-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0002_alertebatiment_auteur_alertegenerale_auteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbreisole',
            name='commentaire',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='arbrereboise',
            name='commentaire',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
