# Generated by Django 4.2 on 2024-01-07 21:59

import UL.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0002_alertepointeau_auteur_alter_alertebatiment_auteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbreReboise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('espece', models.CharField(blank=True, max_length=80, null=True)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('date_reboise', models.DateTimeField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(default='Arbre Reboisé')),
                ('hauteur', models.FloatField(blank=True, null=True)),
                ('diametre', models.FloatField(blank=True, null=True)),
                ('precision', models.TextField(max_length=300)),
                ('secteur', models.CharField(choices=[('NORD', 'Campus Nord'), ('SUD', 'Campus Sud')])),
                ('nature', models.CharField(choices=[('NAT', 'Arbre Fruitier'), ('REBOI', 'Arbre Bois')])),
                ('image', models.ImageField(upload_to='')),
                ('annee_reboise', models.DateField(blank=True, null=True)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=32631)),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('agent_collecteur', models.CharField(blank=True, max_length=50, null=True)),
                ('info_modifier_le', models.DateTimeField(auto_now=True)),
                ('limite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UL.limite')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UL.zone_ul')),
                ('zone_plantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UL.espacevert')),
            ],
            options={
                'verbose_name': 'Arbre Reboisé',
                'verbose_name_plural': 'Arbres Reboisés',
            },
            bases=(UL.models.CodeLatLonGeom, models.Model),
        ),
    ]
