# Generated by Django 4.2.3 on 2023-12-21 15:42

import UL.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0003_alter_zone_ul_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone_ul',
            name='limite',
            field=models.ForeignKey(default=UL.models.Limite, null=True, on_delete=django.db.models.deletion.PROTECT, to='UL.limite'),
        ),
    ]
