# Generated by Django 4.2 on 2024-01-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0003_arbrereboise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertegenerale',
            name='auteur',
        ),
    ]
