# Generated by Django 4.2 on 2024-02-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0004_toiletteisole_info_modifier_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='toiletteisole',
            name='agent_collecteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='toiletteisole',
            name='date_collecte',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
