# Generated by Django 4.2.3 on 2023-12-22 10:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0004_alter_zone_ul_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32631),
        ),
        migrations.AlterField(
            model_name='zone_ul',
            name='aire',
            field=models.FloatField(default=0),
        ),
    ]
