# Generated by Django 4.2 on 2024-01-07 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_profile_type_profile'),
        ('UL', '0004_remove_alertegenerale_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertegenerale',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
    ]
