# Generated by Django 4.2 on 2024-01-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0005_alertegenerale_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertebatiment',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='alertegenerale',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='alertejardin',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='alertelampadaire',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='alertepointeau',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='alertepoubellefosse',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='alertereposoir',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='alertewifi',
            name='auteur',
        ),
    ]
