# Generated by Django 4.2 on 2024-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0005_toiletteisole_agent_collecteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosseseptique',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
