# Generated by Django 4.2.3 on 2023-12-22 12:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0005_alter_batiment_geometrie_alter_zone_ul_aire'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='coordliste',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000000000), blank=True, null=True, size=None),
        ),
    ]
