# Generated by Django 4.2 on 2024-01-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_profile_type_profile'),
        ('UL', '0006_remove_alertebatiment_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertebatiment',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AddField(
            model_name='alertegenerale',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AddField(
            model_name='alertejardin',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AddField(
            model_name='alertelampadaire',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AddField(
            model_name='alertepointeau',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AddField(
            model_name='alertepoubellefosse',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AddField(
            model_name='alertereposoir',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AddField(
            model_name='alertewifi',
            name='auteur',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
    ]
