# Generated by Django 4.2 on 2024-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0006_alter_fosseseptique_info_modifier_le'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosque',
            name='aire',
        ),
        migrations.AlterField(
            model_name='aireloisir',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='aireloisir',
            name='type_usage',
            field=models.CharField(choices=[('Footbal', 'Footbal'), ('Bascketball', 'Bascketball'), ('Voleyball', 'Voleyball'), ('Tenis', 'Tenis'), ('Dance', 'Dance'), ('Auditerium', 'Auditerium')]),
        ),
        migrations.AlterField(
            model_name='airestationnement',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='airestationnement',
            name='type',
            field=models.CharField(choices=[('Moto/Cyclo', 'Moto/Cyclo'), ('Automobile', 'Automobile')]),
        ),
        migrations.AlterField(
            model_name='arbreisole',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbrereboise',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='arbrereboise',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointeau',
            name='source',
            field=models.CharField(choices=[('Forage', 'Forage'), ('Tde', 'Tde')]),
        ),
        migrations.AlterField(
            model_name='reposoir',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationmeteo',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='telecomminication',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='trameverte',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
