# Generated by Django 4.2.3 on 2023-12-22 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0006_batiment_coordliste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='coordliste',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
