# Generated by Django 4.2 on 2024-02-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0007_remove_kiosque_aire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosque',
            name='aire',
            field=models.FloatField(default=0),
        ),
    ]
