# Generated by Django 4.2.3 on 2023-12-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0007_alter_batiment_coordliste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batiment',
            name='coordliste',
        ),
    ]
