# Generated by Django 4.2.3 on 2023-12-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0008_remove_batiment_coordliste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assainissement',
            name='type',
            field=models.CharField(choices=[('PBL', 'Poubele'), ('FOS', 'Fosse septique')], max_length=30),
        ),
    ]
