# Generated by Django 4.2 on 2024-02-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0008_kiosque_aire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosque',
            name='aire',
        ),
    ]
