# Generated by Django 4.2 on 2024-02-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0009_remove_kiosque_aire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airestationnement',
            options={'verbose_name': 'Aire de stationnement'},
        ),
    ]
