# Generated by Django 4.2 on 2024-02-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0010_alter_airestationnement_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batis',
            old_name='adresse',
            new_name='commentaire',
        ),
        migrations.AlterField(
            model_name='airerepos',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bassineau',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='batis',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='eclairage',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiosque',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitegeographique',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='panneau',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointeau',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='poubelle',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationmeteo',
            name='commentaire',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='toiletteisole',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='voirie',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='info_modifier_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
