# Generated by Django 4.2 on 2024-02-24 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0011_rename_adresse_batis_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batis',
            name='domaine_formation',
            field=models.CharField(blank=True, choices=[('Hybride/Polyvalent', 'Hybride/Polyvalent'), ('Santé', 'Santé'), ('Economie', 'Economie'), ('Homme/Societé', 'Homme/Societé'), ('Sport', 'Sport'), ('Informatique', 'Informatique'), ('Agronomie', 'Agronomie'), ('Langue et Art', 'Langue et Art'), ('Communication', 'Communication'), ('Droit/Politique', 'Droit/Politique')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='toiletteisole',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.PointField(srid=32631),
        ),
    ]
