# Generated by Django 4.2 on 2024-02-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0012_alter_batis_domaine_formation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toiletteisole',
            name='aire',
        ),
    ]
