# Generated by Django 4.2 on 2024-02-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0013_remove_toiletteisole_aire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Telecomminication',
            new_name='Telecommunication',
        ),
    ]
