# Generated by Django 4.2 on 2024-02-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0014_rename_telecomminication_telecommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='panneau',
            name='couleur',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
