# Generated by Django 4.2 on 2024-03-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0015_panneau_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbrereboise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
