# Generated by Django 4.2 on 2024-03-16 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0016_alter_arbrereboise_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbrereboise',
            name='image',
        ),
    ]
