# Generated by Django 4.2 on 2024-04-27 21:04

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_profile_type_profile'),
        ('UL', '0017_remove_arbrereboise_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poubelle',
            options={'verbose_name': 'Poubelle', 'verbose_name_plural': 'Poubelles'},
        ),
        migrations.AlterField(
            model_name='alertebatiment',
            name='SOSMessage',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alertebatiment',
            name='auteur',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertebatiment',
            name='disfonction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertebatiment',
            name='lesPennes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Climatisation', 'Climatisation'), ('Ventilateur', 'Ventilateur'), ('Ampoule', 'Ampoule'), ('Sonorisation', 'Sonorisation'), ('Table/Banc', 'Table/Banc')], max_length=300),
        ),
        migrations.AlterField(
            model_name='alertegenerale',
            name='SOSMessage',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alertegenerale',
            name='auteur',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertegenerale',
            name='disfonction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertejardin',
            name='SOSMessage',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alertejardin',
            name='auteur',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertejardin',
            name='disfonction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertelampadaire',
            name='SOSMessage',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alertelampadaire',
            name='auteur',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertelampadaire',
            name='disfonction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertepointeau',
            name='SOSMessage',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alertepointeau',
            name='auteur',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertepointeau',
            name='disfonction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertepoubelle',
            name='SOSMessage',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alertepoubelle',
            name='auteur',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertepoubelle',
            name='disfonction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertereposoir',
            name='SOSMessage',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alertereposoir',
            name='auteur',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertereposoir',
            name='disfonction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alertewifi',
            name='SOSMessage',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alertewifi',
            name='auteur',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateurs.profile'),
        ),
        migrations.AlterField(
            model_name='alertewifi',
            name='disfonction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poubelle',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='poubelle',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
