# Generated by Django 4.2 on 2024-11-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UL', '0018_alter_poubelle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airestationnement',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
